### ISSUE TITLE
RDS

### ISSUE THREAD

**Issue by mabaoweibbq** [JesperGrud/snRNAseq_eWAT#1]
could you tell me how to download the rds files
LFD_R1.dgecounts.rds
LFD_R2.dgecounts.rds
HFD_R1.dgecounts.rds
HFD_R2.dgecounts.rds

Best wishes

**Comment by JesperGrud** [comment]
Those files are equivalent to the raw count matrices hosted on GEO. The link to the GEO submission is in the README or here: https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE160729

Best regards,
Jesper

**Comment by mabaoweibbq** [comment]
Thanks
Could you upload the Ensembl_Mouse.txt file？
Best regards

**Comment by mabaoweibbq** [comment]
Genes <- read.delim("Ensembl_Mouse.txt")
