### ISSUE TITLE
Ensembl_Mouse.txt file

### ISSUE THREAD

**Issue by mabaoweibbq** [JesperGrud/snRNAseq_eWAT#2]
Thanks for your help.
1 I download the GSE160729_RAW.tar，but the scripts needs the 
"
LFD_R1 <- readRDS("~/LFD_R1.dgecounts.rds") # Equivalent to count matrices on GEO
# Extracting intron+exons counts 
LFD_R1 <- LFD_R1$umicount$inex$all
LFD_R2 <- LFD_R2$umicount$inex$all 
HFD_R1 <- HFD_R1$umicount$inex$all 
HFD_R2 <- HFD_R2$umicount$inex$all”
How to generate the RDS file?

2.Could you upload the Ensembl_Mouse.txt file？
  Genes <- read.delim("Ensembl_Mouse.txt")

**Comment by JesperGrud** [comment]
Hi,

Sorry for the delay in getting back to you.

Ad 1: You can read .mtx (MatrixMarket) files in R using the Matrix library. These matrices are equivalent to 'LFD_R1$umicount$inex$all'. So your code could be: LFD_R1 <- readMM("GSM4878207_LFD_E1.mtx"). You should then also import row and column names which are stored in the two additional files (rownames: GSM4878207_LFD_E1.genes.txt, column names: GSM4878207_LFD_E1.barcodes.txt).

Ad 2: I have uploaded the request file to the OSF repository. Please find the link to OSF on the front page of this GitHub repository.

If you need additional help, please reach out on email (jgsm@bmb.sdu.dk).

Best regards,
Jesper
