### ISSUE TITLE
Wrong URL for Adipocytes.Rds

### ISSUE THREAD

**Issue by dksenthil** [JesperGrud/snRNAseq_eWAT#3]
Hi All,  the URL for Immune and Adipocytes seurat object are mixed up e.g. for Adipocytes https://osf.io/6eh8d/download

Also If I load and do a simple DotPlot I get indexing error for eWAT_Adipocytes.Rds.  eWAT_FAP.Rds seems fine. My guess eWAT_Adipocytes RDS is corrupt!

`temp.obj<- readRDS("eWAT_Adipocytes.rds")`

```
 DotPlot(
    Adipocytes.obj,
   features = c("Fn1"),
    cols = c("gray", "red")
  )
Warning: Could not find Fn1 in the default search locations, found in RNA assay instead
Error in intI(j, n = d[2], dn[[2]], give.dn = FALSE) : 
  invalid character indexing
In addition: Warning message:
In cells.idents["NA"] <- names(x = which(x = is.na(x = Idents(object = object)[cells]))) :
  number of items to replace is not a multiple of replacement length
```

**Comment by JesperGrud** [comment]
Thank you for noticing. The links have now been corrected. 

The make the DotPlot function work you need to set labels into the ident slot of the Seurat object first.
Adipocytes.object <- readRDS("eWAT_Adipocytes.Rds")
Adipocytes.object<- SetIdent(Adipocytes.object, value = Adipocytes.object$Label)
DotPlot(Adipocytes.object, features = "Fn1")

I'm closing the issue now, but please make a new one or re-open it, if it is not working for you.
