### ISSUE TITLE
UMAP reduction missing for Adipogenesis

### ISSUE THREAD

**Issue by dksenthil** [JesperGrud/snRNAseq_eWAT#4]
Hi, I'm interested in plotting the umap projections for Adipogeneis subluster. I see "pca", "harmony" and "phate" in the subset  eWAT_Adipogenesis.Rds but not "umap"

**Comment by JesperGrud** [comment]
Hi,

We didn't use the UMAP embedding for the primary analysis of adipogenesis. You can create a UMAP embedding using the harmonized PCs. For example:
Adipogenesis.object <- RunUMAP(Adipogenesis.object, reduction = "harmony", dims = 1:20)

You will need to find out how many dimensions to use. In the above code I suggested 20, which in our hands often works decently, but it can be worth it to explore how your analysis changes by using a different number of dimensions for embedding.

I'm closing this issue now, but please create a new one or re-open it if its not working for you.
